FROM registry.gitlab.com/appsbytherealryanbonham/open-realty-docker:0.0.11

ENV APACHE_DOCUMENT_ROOT /app/src

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# RUN adduser deploy
RUN chmod -R 777 /tmp

COPY ./ /app

WORKDIR /app

RUN yarn install

# Install composer dependencies
RUN ./composer_install.sh

RUN php composer.phar install --no-dev 

RUN touch /app/src/devignoreinstall
EXPOSE 80
